version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: sigmasoft-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sigmasoft_db
      MYSQL_USER: sigmasoft
      MYSQL_PASSWORD: 1920sigmasoft
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
